# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SHKr0_VwyyDtWI8U_qiPWJ8WeYerwYz
"""

import pandas as pd

data={
    "ism":["Nozila" , "Shalola" ,"Shohsanam" , "Ixtiyor", "Mohigul" ],
    "Familya":["Mirzakarimova" ,"Bekmirzayeva" ,"Mahmudova" ,"Isroiljonov" ,"Orolxonova" ],
    "Jinsi":["Ayol" ,"Ayol" ,"Ayol" ,"Erkak" ,"Ayol"],
    "Yoshi":[19,19,19,21,19],
    "Kurs":[2,2,2,4,2],
    "Manzil":["Oqjar MFY" ,"Buvayda","Azimobod Mfy" , "Fargona" ,"Quvasoy"]
}

baza = pd.DataFrame(data)
print (baza)